spring:
  datasource:
    password: ${DB_PASSWORD:gsilva11}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dsvendas}
    username: ${DB_USER:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
